version: '3'

services:
  certbot:
    image: ghcr.io/richardds/certbot
    build:
      dockerfile: Dockerfile
      context: .
      args:
        - ALPINE_VERSION=3.17
        - CERTBOT_CLOUDFLARE_VERSION=2.3
    volumes:
      - ./certificates:/etc/letsencrypt
      - ./cloudflare.ini:/cloudflare.ini:ro
