name: Docker

on:
  pull_request:
  push:
    tags:
      - '*'

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v3
      -
        name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0

  docker:
    needs: lint
    runs-on: ubuntu-22.04
    env:
      DOCKER_BUILD_ARGS: |
        ALPINE_VERSION=3.17
        CERTBOT_VERSION=1.32
        CERTBOT_CLOUDFLARE_VERSION=2.3
      DOCKER_TAGS: |
        richardboldis/certbot:latest
        richardboldis/certbot:${{ github.ref_name }}
        ghcr.io/richardds/certbot:latest
        ghcr.io/richardds/certbot:${{ github.ref_name }}
    steps:
      -
        name: Setup Docker
        uses: docker/setup-buildx-action@v2
      -
        if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
        name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          build-args: ${{ env.DOCKER_BUILD_ARGS }}
      -
        if: startsWith(github.ref, 'refs/tags/')
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        if: startsWith(github.ref, 'refs/tags/')
        name: Login to GitHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      -
        if: startsWith(github.ref, 'refs/tags/')
        name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          build-args: ${{ env.DOCKER_BUILD_ARGS }}
          tags: ${{ env.DOCKER_TAGS }}
          push: true
