name: Docker

on:
  push:
    tags:
      - '*'
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      -
        name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0

  docker:
    runs-on: ubuntu-22.04
    steps:
      -
        name: Setup Docker
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          build-args: |
            ALPINE_VERSION=3.16
          push: true
          tags: |
            richardboldis/certbot:latest
            richardboldis/certbot:${{ github.ref_name }}
            ghcr.io/richardds/certbot:latest
            ghcr.io/richardds/certbot:${{ github.ref_name }}
